name: Deploy to Dokku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # <-- IMPORTANTISSIMO per evitare shallow update

      - name: Setup SSH for Dokku
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOKKU_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan 164.68.99.198 >> ~/.ssh/known_hosts

      - name: Push to Dokku
        run: |
          git remote add dokku dokku@164.68.99.198:apps || git remote set-url dokku dokku@164.68.99.198:apps
          git push dokku main --force
